### ISSUE TITLE
Error when clicking on an item in the tray

### ISSUE THREAD

**Issue by SecretSquirrel77** [teroparvinen/foundry-action-pack#1]
Amazing approach to an action tray, bravo! 

Foundry V10, DnD5e 2.0.3, all modules updated (lots of modules)
When clicking on any item in the action tray, the following error pops up in the console. Other than throwing an error, it doesn't appear to cause any issues. Otherwise appears to be working as intended. 
![image](https://user-images.githubusercontent.com/77705375/204050467-826efa85-7d5f-4e72-afd4-fc1904bf8614.png)
Unsure if the intent was to make the item description expand on click or not, but if not, this would be a nice enhancement.

**Comment by teroparvinen** [comment]
Thanks for the report. This is a v10 upgrade regression issue, I will look into it. It is indeed intended to expand the description.
