### ISSUE TITLE
[Feature Request] Show Cantrips in Tray

### ISSUE THREAD

**Issue by SirMotte** [teroparvinen/foundry-action-pack#10]
Thank you for this awesome module, I feel like this is the fastest to use one out there with similar functionality!

The only grievance I have is that cantrips are not shown in the Tray as they can only be activated as "prepared" when going into the spell settings (alternatively set ti always prepared). While this certainly is not much of a hassle I'd appreciate if they would be included as well, either optionally or by default.

**Comment by teroparvinen** [comment]
I will make this a setting.

**Comment by SirMotte** [comment]
> I will make this a setting.

Awesome, thank you :).
