### ISSUE TITLE
Spells don't appear for Fighter with spells from feat

### ISSUE THREAD

**Issue by JulieWinchester** [teroparvinen/foundry-action-pack#12]
This looks great, thanks for creating it! I may have found a possible bug? I have a Fighter PC with spells from the feat Shadow Touched. Even though the spells are in his spellbook on his character sheet, they do not show up in the action pack list.

**Comment by teroparvinen** [comment]
The items that appear must have a) an activation cost (action, bonus action...) and b) in the case of spells be castable. Being castable means it is properly prepared or does not need to be prepared.

For Shadow Touched, I recommend this: Drag the spell onto the character sheet so it gets added to the spell book. Then set it to "Innate Spellcasting" and give it limited uses 1/1 (Long rest). This is a fighter, so skip the next step but including it in case someone comes back to this later. If the character is a spellcaster, drag another copy of the spell onto the sheet and set it to be "Always prepared" so it can be cast with regular slots.

Anything other than this is a bug. Drop a comment and I'll reopen the issue.

**Comment by JulieWinchester** [comment]
Thanks for the suggestion, that works in this specific case. But I do still think there might be a bug here, in that it seems like At Will spells are not shown in Action Pack at all? If I go to a spellcaster and edit one of their cantrips and play around with spell preparation mode, every mode appears in the Action Pack list except At Will. This was with Mage Hand, which has an activation cost.

**Comment by teroparvinen** [comment]
You are correct. It has been fixed and will be in the next version. Thanks for the report.
