### ISSUE TITLE
"At-Will" Spells Don't Appear in Panel

### ISSUE THREAD

**Issue by n-depinto** [teroparvinen/foundry-action-pack#13]
Thanks for the awesome module!

I have noticed that spells with the "At-Will" preparation mode don't appear in the panel. Not sure if this was intentional, but would it be possible to have these spells show up on the panel, as well?

**Comment by teroparvinen** [comment]
Duplicate of #12

**Comment by teroparvinen** [comment]
This is fixed and will be in the next update

**Comment by n-depinto** [comment]
Amazing! Thank you for your work!
