### ISSUE TITLE
Consider changing spell slots into clickable dots

### ISSUE THREAD

**Issue by Ikabodo** [teroparvinen/foundry-action-pack#16]
![image](https://user-images.githubusercontent.com/7766890/206722766-4eb7c98e-cf04-429c-8e2d-0e85ddf3024c.png)

You might want to consider changing these numbers into visual aids. For example dots that are filled when available, this would make it easier to visually see how many spellslots you have left. _Optionally you can can click an filled in one to spend it, or click an empty one to give a slot back._

![image](https://user-images.githubusercontent.com/7766890/206722872-ed68c298-4da7-41f0-8c56-09d621c677c7.png)

Also, you might want to add the ability to minimize categories. This is especially useful for wizards or clerics with a lot of spells available.

**Comment by teroparvinen** [comment]
Thanks for the suggestion. Dots are in (the next update).

Didn't go for the collapsible categories yet, because the whole idea is to have things readily available. New options for a more condensed layout will be available and should help the casters.
