### ISSUE TITLE
Cantrips must be marked as prepared

### ISSUE THREAD

**Issue by rayd99** [teroparvinen/foundry-action-pack#17]
Action Pack will not show spells that are not marked prepared - even Cantrips which are by definition always prepared.

WORKAROUND: Setting Cantrips to Always Prepared does make them show up, but it's not how they're coded by default in either the WIRE SRD or the base SRD.

**Comment by teroparvinen** [comment]
There's a setting in the latest version that allows you to show cantrips even if they are unprepared. Maybe I should make it be on by default. Thanks for the feedback, I will give this some thought.
