### ISSUE TITLE
[Feature Requests – super low priority] Sort items and open item sheet

### ISSUE THREAD

**Issue by LukasPrism** [teroparvinen/foundry-action-pack#19]
Hiya

Thanks so much for making the slimmer panel options – perfection!

Just a couple of little QOL suggestions:

One would be an option to sort items alphabetically (we have a module doing that for our character sheets for so long I forgot it wasn't core).

Secondly, if there was a way to open the item sheet from the panel that would save digging around in the character sheet. Sorry if I've missed something. Token Action HUD does it on right-click but you have that rolling the item, so perhaps an option between the two? Rolling on a right click does take some getting used to (it's usually for context menus), but I can see how folk could be into it.

Many thanks again for this wonderful module!

**Comment by teroparvinen** [comment]
Thanks, sorting is a nice idea for the next update.

> Secondly, if there was a way to open the item sheet from the panel that would save digging around in the character sheet. 

Middle click, Tidy 5e style. I would have gone completely crazy without this a long time ago developing WIRE.

**Comment by LukasPrism** [comment]
Ah thanks! As a mac user I never think to middle click (you cannot with Apple hardware). I do use a Logi mouse with Foundry during game sessions tho so that’s fine. Note that MacBook users won’t be able to middle-click  – I know there are some in the discord but probably not a big deal. Cheers!
