### ISSUE TITLE
[Suggestion] Add Compatibility with the ItemMacro module even when WIRE is not installed

### ISSUE THREAD

**Issue by FurtherV** [teroparvinen/foundry-action-pack#27]
Currently, there is an issue with the Action Pack module and the ItemMacro module that, when WIRE is not installed, the item macro on an item gets never called, even with all the hooks and settings in the ItemMacro module enabled. 

Rolling the item via the sheet runs the macro, which is the intended behavior. But if you roll the same item via the Action Pack then the macro is simply ignored. It would be great if this could be changed so that the ItemMacro is run instead if a specific setting is turned on and WIRE not installed since your Action Pack is great, even for low to no automation games that do not use WIRE.

**Comment by Tatonker** [comment]
This would be a great addition. My players prefer the look and feel of this to the current HuD we're using but I'm not ready to switch fully over due to this itemmacro issue.

**Comment by Narbis** [comment]
I would also like to see compatibility added for ItemMacro, but in the meantime I made a janky workaround that solves the problem until a more robust implementation can be developed. If you're interested, you can find the download manifest here: https://github.com/narbis/foundry-action-pack/releases/latest/download/module.json
