### ISSUE TITLE
Add Skill Checks

### ISSUE THREAD

**Issue by roleoutgames** [teroparvinen/foundry-action-pack#3]
The Action Tray is very nicely formated but it seems to be missing the most common use of skill checks. Yes, you could roll a dexterity check, but not having a button that says Stealth Check adds an extra step for my players. Do you plan to integrate skills?

**Comment by teroparvinen** [comment]
Thanks for the comment.

At this time, it is a conscious decision not to include skills here. I do have a separate module for that which I intend to release some time soon.
