### ISSUE TITLE
Suggestion: Add support for custom sections

### ISSUE THREAD

**Issue by Ikabodo** [teroparvinen/foundry-action-pack#30]
Some classes, such as monks, have quite a few features as their abilities. This can clog down and create a long list of features.

Some possible solutions:
1. Add a way to add custom sections to items through to this module itself.
2. Add a way to create custom sections and reorder items & categories in the bar manually. 
3. Add support for "Custom Sections" module as an option. 

_Thank you for a great module!_

**Comment by Ikabodo** [comment]
Any update on this? I took a look at the code and saw the groups under for example spells. It looks pretty well implemented. 

Would it be possible to enable support for "customer character sections"? Or if that is too much, maybe consider adding the newly implemented feature detail?
![image](https://github.com/teroparvinen/foundry-action-pack/assets/7766890/f42e5c9f-257a-47f9-9372-414d80a7688b)

**Comment by teroparvinen** [comment]
To be honest, I had missed the feature detail option completely. This definitely fits the bill for Action Pack, I will see if I can find the time to put that in sometime soon. Thanks for the heads up!
