### ISSUE TITLE
Warnings generated with dnd5e v2.2.1

### ISSUE THREAD

**Issue by T-Whiz** [teroparvinen/foundry-action-pack#34]
In dnd5e v2.2.1 the following warning is generated 6 times each time a token is selected. Everything still appears to work as expected, the impact is only a very large amount of warning text in the console.
`Error: The value of CONFIG.DND5E.abilities has been changed to an object. The former value can be acccessed from .label.`

Verified this occurs with no other modules enabled.
Foundry v10.291
dnd5e v2.2.1
Action Pack v10.7
The Forge v1.10

![image](https://github.com/teroparvinen/foundry-action-pack/assets/101904996/7dfb8035-3c8b-41c3-bc5a-7386ef45fede)

**Comment by YenBenGrey** [comment]
I am also getting this in v11
