### ISSUE TITLE
Pact Magic/Magic item spells do not show up in tray

### ISSUE THREAD

**Issue by Orionox** [teroparvinen/foundry-action-pack#4]
Any spells that are set as pact magic don't show up in the tray. Additionally, any spells that are added to a character sheet via the mod Magic items do not appear on the tray.

**Comment by teroparvinen** [comment]
Thanks for the report. Warlocks should now find the module a bit more useful.

The Magic Items module is new to me but looks interesting. I will look into it and see what can be done.

**Comment by PwQt** [comment]
Just FYI, i know that's closed - users have asked me for support, MI has been deprecated for Foundry V11, probably dnd3.0, I've been running a fork of that: https://github.com/PwQt/magic-items-2
