### ISSUE TITLE
MidiQol Support

### ISSUE THREAD

**Issue by cadowtin** [teroparvinen/foundry-action-pack#5]
I believe the issue I have is MidiQol Related, but I have no way to roll things that involve attacks

**Comment by teroparvinen** [comment]
Can you provide any more details? The module calls the item `use` method to activate an item, there is very little that can go wrong here. I don't use Midi-qol myself so I can't offer more advice.

**Comment by cadowtin** [comment]
NVM, was a personal issue, my bad.
