### ISSUE TITLE
[enhancement] Allow panel when no token is selected

### ISSUE THREAD

**Issue by cstby** [teroparvinen/foundry-action-pack#8]
Most players only have one character, and that character's panel is the only one they will ever use. There are situations where players might want to use items or abilities without access their token (e.g. theatre of mind combat, a map scene, or a landing page.) In these cases, it would be a major convenience to have access to the panel with no token selected.

Foundry expects players to select a single character in their "user configuration." Defaulting to this pre-selected character when no token selected could be one approach to meeting this need.

**Comment by teroparvinen** [comment]
Thanks for the idea, this is now live. I decided to make the main character be active whenever nothing else is selected. If you have a common token for the party on the map or something like that, it will need to be deselected to show the items for the character.
